apiVersion: v1
kind: Service
metadata:
  name: grafana-load-balancer
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    component: grafana-server
