apiVersion: v1
kind: Service
metadata: 
  name: prometheus-load-balancer
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  type: LoadBalancer
  ports:
    - name: prometheus-ui
      port: 9090
      targetPort: 9090
    - name: node-export
      port: 9100
      targetPort: 9100
  selector: 
    component: prometheus-server
