apiVersion: v1
kind: ServiceAccount
metadata:
 name: prometheus-monitoring
 namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods" ]
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["*"]
- nonResourceURLs: ["/metrics"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects: 
  - kind: ServiceAccount
    name: prometheus-monitoring
    namespace: monitoring


