apiVersion: v1
kind: Service
metadata: 
  name: prometheus-cluster-ip-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector: 
    component: prometheus-server
