apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-load-balancer
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: kube-state-metrics
